class locators:
    sign_in = '//button[@title="Close"]'
    exp_all = '//*[@data-testid="adv-search-expand-all"]'
    name = 'text-input__7'
    birth_from = 'text-input__8'
    birth_to = 'text-input__9'
    month_date = 'birthday-input'
    trivia = '//button[contains(@data-testid,"TRIVIA")]'
    topic_dd = '//select[contains(@id,"topic-dropdown-id")]/option[6]'
    eg_input = '//input[contains(@id,"input__11")]'
    death_from = 'death-date-start-input'
    death_to = 'death-date-end-input'
    gender = '//button[contains(@data-testid,"-MALE")]'
    include = 'input[data-testid="include-adult-names"]'
    result = 'button[data-testid="adv-search-get-results"]'
    res_data = 'div[data-testid="nlib-title"] a'
